server:
  port: 8082
spring:
  application:
    name: zipkin
  profiles:
    active: csdn
eureka:
  client:
    service-url:
      defaultZone: http://root:i@localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false